on:
  push:
    branches:
      - master
name: Build and Release
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '*' # Use the latest stable version of Go

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: cd cmd/pwgen; go build -v -o pwgen

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          args: 'cmd/pwgen/pwgen'
